In [2]:
import numpy as np

# Intro

In [3]:
# 1D array -> Vector
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
# 2D array -> Matrix
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# zeros function for initializing
arr3 = np.zeros((2,2))
arr3

array([[0., 0.],
       [0., 0.]])

In [7]:
# ones function for initializing
arr4 = np.ones((3,3))
arr4


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# identity matrix
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# arange function
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr7 = np.arange(2,8)
arr7

array([2, 3, 4, 5, 6, 7])

In [11]:
arr8 = np.arange(1,10,2)
arr8

array([1, 3, 5, 7, 9])

In [12]:
# linear space random number
arr9 = np.linspace(1,10,4)
arr9

array([ 1.,  4.,  7., 10.])

In [13]:
# can copy array function
arr10 = arr9.copy()
arr10

array([ 1.,  4.,  7., 10.])

# Numpy Attributes

In [15]:
# shape attribute
arr1.shape

(5,)

In [16]:
arr2.shape

(2, 3)

In [18]:
arr11 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
arr11.shape

(2, 2, 2)

In [20]:
arr11.ndim

3

In [21]:
arr1.ndim

1

In [22]:
arr2.ndim

2

In [23]:
# size
arr1.size

5

In [24]:
arr11.size

8

In [26]:
# item size
arr2.itemsize

8

In [27]:
arr1.itemsize

8

In [28]:
# dtype
arr1.dtype

dtype('int64')

In [29]:
# astype
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [30]:
arr1.dtype

dtype('int64')

# List Vs Array


1.   Faster
2.   Convenient

1.   Less Memory





In [38]:
# size comparison
lista = range(100)
arr12 = np.arange(100)

In [32]:
import sys

In [36]:
print(sys.getsizeof(52)*len(lista))

2800


In [37]:
print((arr12.itemsize)*(arr12.size))

800


In [39]:
# speed comparison
import time

In [42]:
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()

c = [(x,y) for x,y in zip(x,y)]

print(time.time() - start_time)

3.8000800609588623


In [43]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time = time.time()

c = a+b

print(time.time() - start_time)

0.07511568069458008


# Indexing, Iteration, Slicing

In [45]:
arr13 = np.arange(24)
arr13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [62]:
arr13a = arr13.reshape(6,4)

In [49]:
arr1

array([1, 2, 3, 4, 5])

In [53]:
arr1[2]

3

In [54]:
arr1[1:3]

array([2, 3])

In [55]:
arr1[-1]

5

In [63]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# gives row
arr13a[2]

array([ 8,  9, 10, 11])

In [65]:
# gives column
arr13a[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [68]:
# for individual
arr13a[2,1:3]

array([ 9, 10])

In [70]:
arr13[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [71]:
# iteration
for i in arr13:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [72]:
for i in np.nditer(arr13):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
