In [12]:
import numpy as np

## Numpy Operations

In [13]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([5,6,7,8,9,10])

In [14]:
arr1-arr2

array([-4, -4, -4, -4, -4, -4])

In [15]:
arr1+arr2

array([ 6,  8, 10, 12, 14, 16])

In [16]:
arr1*arr2

array([ 5, 12, 21, 32, 45, 60])

In [17]:
# scaler multiplication
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [18]:
arr1>4

array([False, False, False, False,  True,  True])

In [19]:
# dot product
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [20]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [23]:
arr4.max()

11

In [24]:
arr4.min()

6

In [25]:
arr4.min(axis=0)

array([6, 7])

In [26]:
arr4.mean()

8.5

In [27]:
arr4.mean(axis=0)

array([8., 9.])

In [28]:
arr4.sum()

51

In [30]:
arr4.sum(axis=1)

array([13, 17, 21])

In [31]:
arr4.std()

1.707825127659933

In [32]:
np.median(arr4)

8.5

In [33]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [34]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])