In [1]:
import numpy as np

In [2]:
# reshape
arr1=np.arange(6,12).reshape(2,3)

In [3]:
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
# transpose
arr1.transpose()

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [6]:
# ravel for making 1d array
arr1.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [7]:
# staking for combine two arrays
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
arr2=np.arange(12,18).reshape(2,3)

In [9]:
arr2

array([[12, 13, 14],
       [15, 16, 17]])

In [10]:
np.hstack((arr1,arr2))

array([[ 6,  7,  8, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17]])

In [11]:
np.vstack((arr1,arr2))

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [12]:
# split arrays
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.hsplit(arr1,3)

[array([[6],
        [9]]),
 array([[ 7],
        [10]]),
 array([[ 8],
        [11]])]

In [14]:
np.vsplit(arr1,2)

[array([[6, 7, 8]]), array([[ 9, 10, 11]])]

## Fancy Indexing

In [15]:
arr3=np.arange(12).reshape(3,4)

In [16]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr3[[0,1]]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
arr3[:,[1,2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

# Indexing with boolean arrays

In [23]:
import random

In [25]:
# it works like masking
arr4=np.random.randint(low=20,high=80,size=24).reshape(4,6)

In [28]:
arr4

array([[49, 53, 39, 26, 75, 63],
       [57, 45, 74, 30, 59, 23],
       [69, 63, 48, 72, 60, 27],
       [66, 52, 46, 24, 24, 51]])

In [29]:
arr4[0][2]

39

In [30]:
arr4>60

array([[False, False, False, False,  True,  True],
       [False, False,  True, False, False, False],
       [ True,  True, False,  True, False, False],
       [ True, False, False, False, False, False]])

In [31]:
arr4[arr4>60]

array([75, 63, 74, 69, 63, 72, 66])

In [32]:
arr4[(arr4>60)&(arr4%2!=0)]

array([75, 63, 69, 63])